dist: xenial
language: python
python: "3.7"
addons:
  apt:
    sources:
    - sourceline: "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main"
      key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
    packages:
    - clang-format-9
    update: true
before_install:
  - git config --global clangFormat.binary clang-format-9
  - npm install -g markdownlint-cli
  - pip install Sultan scan-build black
env:
  - RTI_PACKAGE_VERSION=6.0.0 RTI_MIN_PACKAGE_URL=https://rticommunity.s3.amazonaws.com/downloads/continuous-integration/connext-dds/6.0.0/rti_connext_dds-6.0.0-min-x64Linux3gcc5.4.0.zip

install:
  - 'if [ -n "$RTI_MIN_PACKAGE_URL" ]; then resources/travis/linux_install.py; fi'
  - pip3 install .
script: pytest test/python
